Switch bindings to load from a dynamic library without compiling source (#40)
Fixes #39

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,8 +8,6 @@ jobs:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v5
-        with:
-          submodules: true
       - name: Cargo fmt
         run: cargo fmt --all -- --check
       - name: Cargo clippy
@@ -23,8 +21,6 @@ jobs:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v5
-        with:
-          submodules: true
       - uses: dtolnay/rust-toolchain@nightly
       - name: Generate minimal-version dependencies
         run: cargo -Zminimal-versions generate-lockfile
@@ -40,12 +36,13 @@ jobs:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v5
-        with:
-          submodules: true
+      - name: Checkout submodule
+        # Manually update submodules with --checkout because they are configured with update=none and will be skipped otherwise
+        run: git submodule update --recursive --init --force --checkout
       - name: Clean
         run: rm sys/src/*bindings.rs
       - name: Generate
-        run: cargo b -p fidelityfx-sys -Fgenerate-bindings
+        run: cargo r -p api_gen
       - name: Upload crate source
         uses: actions/upload-artifact@v4
         with:
@@ -56,4 +53,4 @@ jobs:
         run: |
           # Somehow bindgen seems to output LF on Windows, and that confuses our status checks which expect CRLF
           unix2dos sys/src/*bindings.rs
-          test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with 'cargo b -p fidelityfx-sys -Fgenerate-bindings'!"; git diff; false)
+          test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with 'cargo r -p api_gen'!"; git diff; false)
